Update org references
clinicjs/node-clinic-bubbleprof pull request #378
Opened 2021-05-19 23:16 UTC by jasnell

/cc @mcollina @conoro

2021-05-20 13:03 UTC, mcollina requested changes

2021-05-20 13:03 UTC, mcollina commented on CODE_OF_CONDUCT.md
> +[clinic]: mailto:report@clinicjs.org
does this email exist?

2021-05-20 13:03 UTC, mcollina commented on index.js
> +      // nearFormLogo: nearFormLogoFile,
just remove this line

2021-05-20 13:03 UTC, mcollina commented on index.js
> +    // const nearFormLogoFile = fs.createReadStream(nearFormLogoPath)
remove this line

2021-05-21 17:10 UTC, jasnell commented on CODE_OF_CONDUCT.md
> +[clinic]: mailto:report@clinicjs.org
Yes it does.

2021-05-21 17:12 UTC, jasnell commented on index.js
> +    // const nearFormLogoPath = path.join(__dirname, 'visualizer', 'nearform-logo.svg')
```suggestion
```

2021-05-21 17:12 UTC, jasnell commented on index.js
> +    // const nearFormLogoFile = fs.createReadStream(nearFormLogoPath)
```suggestion
```

2021-05-21 17:12 UTC, jasnell commented on index.js
> +      // nearFormLogo: nearFormLogoFile,
```suggestion
```

2021-05-21 21:43 UTC, mcollina approved these changes
lgtm

2021-05-21 22:54 UTC, merged